### PR TITLE
Fix/489

### LINKED ISSUE #489: Adjust SES labels depending on group selected
SES is not available for all subgroups (e.g. Asia, non-poor, poor, male, female).  currently, the X axis label says "{SUBGROUP} socioeconomic status" (e.g. "Asian students' families socioeconomic status")

when SES is not available for a given subgroup, the X axis label should read "Overall families' socioeconomic status".

In the comparison dialog, the hint text for "Socioeconomic status" also needs to be updated, to reflect the current subgroup or display "overall" for subgroups with no related SES.  The wording should also update when a gap is selected, to reflect that the value is a gap in SES and not the SES for any specific subgroup

### PR DESCRIPTION
**Pull request by touchRED**
Fixes #489, adjusting the socioeconomic status subtitle/values in the comparison table as well as the x-axis on certain primary and secondary charts.

Viewable [here](https://compassionate-feynman-49dcdf.netlify.app/).

Notes:

- I noticed something weird going on with the secondary chart for the White-Hispanic gap – the "no gap" line is not appearing in the right place. Obviously it should be on the left side, before +1. Pretty sure there's no way this PR introduces the bug, so I'll do some snooping and see if I can find where it cropped up. 

image

- This PR introduces two new functions `getSesHintFromDemographic` and `getAccessor` that handle the ways SES behaves differently depending on demographics. They live in `CompareTable.js` right now but I can move them wherever works best. 
- The logic in `getAccessor` is very similar to `getSecondaryVarName` in `app/selectors/data`, but differs in that it only makes male and female demographics use `all_ses`, while poor and non poor continue using their own ses values that return N/A

QA Criteria from @Lane:
> 
> # Compare Dialog
> under socioeconomic status table header, for subgroups:
> 
> * all, male, or female: Average SES among all families in the community
> * white, black, hispanic, asian, or native american: Average SES among all `{{SUBGROUP}}`  families in the community
> * poor or non-poor: Average SES not available for `{{SUBGROUP}}` families
> * gaps (except for poor - non-poor): Average `{{GAP}}` gap SES in the community
> * poor - non-poor gap: Average `{{GAP}}` gap in SES not available
> 
> the values in the table should correspond to the label, e.g:
> 
> * all, male, or female: uses `all_ses` value
> * white, black, hispanic, asian, or native american uses `{{SUBGROUP}}_ses` value (e.g. `w_ses` for white SES)
> * poor or non-poor show "N/A" for all locations (if you use `p_ses` and `np_ses` it should show "N/A" because those values are not available)
> * gaps show gap value where avaialble `{{GAP}}_ses` (e.g. `wb_ses` for white - Black SES)
> * gaps with no SES value (eg. poor - non-poor) show "N/A"
> 
> # Chart Axis
> * all, poor, non-poor, male, or female: "Average families' socioeconomic status"
> * white, black, hispanic, asian, or native american: "`{{SUBGROUP}}` Families' Socioeconomic Status"
> * gaps: "`{{GAP}}` Gap in Socioeconomic Status"

### CODE REVIEW

**Review by Lane — COMMENTED** [review]
@touchRED labels look great!

one thing i'm noticing is that the location markers overlays are not being positioned correctly when `Asian` is selected as the subgroup.

To replicate, go to:
https://compassionate-feynman-49dcdf.netlify.app/#/chart/none/counties/avg/ses/a/8/33.77/-117.84

and hover over some of the dots.  note that the hovered dot is placed in the top left instead of overtop of where the dot should be.

this only happens with the Asian subgroup, so i think it is an artifact to us not previously having an SES value for Asian families.  i'm good to merge this as is and create a separate issue if you would prefer that,  let me know.

**Comment by touchRED** [comment]
@Lane that's strange – now that you mention it there's also a similar bug happening in the secondary chart for Poor - Non-poor gap (hovering over a dot places the highlighted dot to the right of where it should be):

image

looking into this! thanks for the catch

**Comment by touchRED** [comment]
@Lane you were right about `a_ses` introducing some problems – it looks like these values are strings in the data. I'm casting them to float at the moment within `getPaddedExtent` but could be worth mentioning to whomever that the data type should be corrected. Either way, hover bug is fixed! Updated at the above [netlify link](https://compassionate-feynman-49dcdf.netlify.app/) as well. 

Screen Shot 2021-01-29 at 6 29 47 PM

**Comment by touchRED** [comment]
Looks like the string issue is the same with `pn_seg` and `wa_ses` (even though we're not showing white-asian gap stats). I also found one instance of `pn_seg` being an empty string: Kusilvak Census Area. This throws off `d3.extent`.

So I added a parseFloat to `getDataExtent` instead of `getPaddedExtent` to make sure empty strings aren't being used to compute the extent (I'm pretty sure `d3.extent` ignores NaN). [Netlify link](https://compassionate-feynman-49dcdf.netlify.app/) updated. Lmk if you think we're good to merge this in. 

image

**Comment by Lane** [comment]
nice, good catch!  this is my bad, i will update the data pipeline so those are cast properly.

**Pull request merged**
